site_name: 容旋坤的个人网站 # 左上角标题

nav: # 目录
  - Notes:
    - Notes/index.md
    - MarkDown: Notes/Markdown.md
    - Git: Notes/Git.md
    - VSCode: Notes/VSCode.md
    - C: Notes/C.md
    - 数据结构: Notes/数据结构.md

theme:
  name: material
  palette: 
    - scheme: slate # 黑暗模式
      primary: blue grey # 顶部的颜色
      accent: amber # 高亮的颜色
      toggle: 
        icon: material/weather-night
        name: 切换至日间模式
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 切换至夜间模式

  language: zh # 中文

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮

  icon: 
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2022 容旋坤 # 左下角的版权声明

edit_uri: edit/main/docs # 编辑按钮跳转的链接

repo_url: https://github.com/Rong-Xuankun/Rong-xuankun.github.io # 右上角点击跳转的链接

repo_name: Rong-Xuankun.github.io # 右上角的名字
