site_name: 容旋坤的个人网站 # 左上角标题

nav:
  - Notes:
    - MarkDown: Notes/Markdown/md
    - Git: Notes/Git.md
    - VSCode: Notes/VSCode.md
    - C: Notes/C.md
    - 数据结构: Notes/数据结构.md

theme:
  name: material
  palette: 
    scheme: slate # 黑暗模式
    primary: blue grey
    accent: blue
  language: zh # 中文
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮

copyright: Copyright &copy; 2022 容旋坤 # 左下角的版权声明

edit_uri: edit/main/docs # 编辑按钮跳转的链接

repo_url: https://github.com/Qiaoyiyu617 # 右上角点击跳转的链接

repo_name: Qiaoyiyu617.github.io # 右上角的名字
